export type Exercise = {
  id: string
  name: string
  name_vi: string
  muscle_group: string
  sets: number
  reps: string
  rest_sec: number
  weight_note: string
  tips: string[]
  avoid: string[]
  gif_url: string
}

export type WorkoutDay = {
  day: string
  day_vi: string
  muscle_groups: string
  duration_min: string
  exercises: Exercise[]
}

export const WORKOUT_PLAN: WorkoutDay[] = [
  {
    day: 'T2',
    day_vi: 'Thứ 2',
    muscle_groups: 'Ngực + Vai',
    duration_min: '45–50',
    exercises: [
      {
        id: 'push-up-wide',
        name: 'Wide Push-Up',
        name_vi: 'Hít đất tay rộng',
        muscle_group: 'Ngực',
        sets: 4,
        reps: '12–15',
        rest_sec: 60,
        weight_note: 'Bodyweight — tập đến gần failure ở set cuối',
        tips: [
          'Tay rộng hơn vai khoảng 1 nắm tay',
          'Giữ core cứng, người thẳng từ đầu đến gót',
          'Hạ người từ từ 2–3 giây, đẩy lên nhanh hơn',
        ],
        avoid: [
          'Không để hông võng xuống',
          'Không khóa khuỷu tay hoàn toàn khi đẩy lên',
        ],
        gif_url: 'https://assets.mixkit.co/videos/preview/mixkit-man-doing-push-ups-at-home-4894-large.mp4',
      },
      {
        id: 'pike-push-up',
        name: 'Pike Push-Up',
        name_vi: 'Hít đất pike (Vai)',
        muscle_group: 'Vai',
        sets: 3,
        reps: '10–12',
        rest_sec: 60,
        weight_note: 'Bodyweight — dần tiến tới Handstand Push-Up',
        tips: [
          'Hình chữ V ngược — mông cao, đầu hướng xuống sàn',
          'Hạ đầu xuống sàn giữa hai tay',
          'Giữ khuỷu tay hướng ra ngoài',
        ],
        avoid: [
          'Không để hông thụt xuống khi đẩy lên',
          'Không hạ quá nhanh, dễ chấn thương vai',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-2.svg',
      },
      {
        id: 'dumbbell-fly',
        name: 'Dumbbell Chest Fly',
        name_vi: 'Tạ đôi mở ngực',
        muscle_group: 'Ngực',
        sets: 3,
        reps: '12',
        rest_sec: 60,
        weight_note: 'Bắt đầu 5–8kg/tay, tăng khi làm đủ 12 rep với form chuẩn',
        tips: [
          'Nằm ngửa, tạ ở hai bên, cong khuỷu nhẹ',
          'Mở rộng cảm nhận căng ngực, không kéo bằng vai',
          'Đóng lại như "ôm cây" — siết ngực ở đỉnh',
        ],
        avoid: [
          'Không duỗi thẳng hoàn toàn khuỷu tay — dễ chấn thương',
          'Không dùng đà lắc người',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-4.svg',
      },
      {
        id: 'lateral-raise',
        name: 'Lateral Raise',
        name_vi: 'Nâng tạ sang ngang',
        muscle_group: 'Vai giữa',
        sets: 3,
        reps: '15',
        rest_sec: 45,
        weight_note: 'Bắt đầu 4–6kg/tay — nhẹ hơn mày nghĩ là đủ',
        tips: [
          'Giữ tạ hơi nghiêng (ngón út cao hơn ngón cái)',
          'Dừng lại ở ngang vai, đừng đưa lên quá',
          'Hạ tạ chậm rãi 3 giây',
        ],
        avoid: [
          'Không nhún vai khi nâng — loại bỏ cơ vai ra',
          'Không dùng momentum lắc người',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-2.svg',
      },
      {
        id: 'incline-push-up',
        name: 'Incline Push-Up',
        name_vi: 'Hít đất nghiêng (phần dưới ngực)',
        muscle_group: 'Ngực dưới',
        sets: 3,
        reps: '15',
        rest_sec: 60,
        weight_note: 'Bodyweight — dùng ghế, bàn cao khoảng 50–70cm',
        tips: [
          'Tay đặt trên mặt phẳng cao, người nghiêng ~45 độ',
          'Giữ core siết, hạ ngực chạm mép bàn',
        ],
        avoid: [
          'Không để khuỷu tay bè quá rộng ra ngoài',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-4.svg',
      },
    ],
  },
  {
    day: 'T3',
    day_vi: 'Thứ 3',
    muscle_groups: 'Lưng + Tay sau',
    duration_min: '45–50',
    exercises: [
      {
        id: 'pull-up',
        name: 'Pull-Up / Assisted Pull-Up',
        name_vi: 'Xà đơn',
        muscle_group: 'Lưng rộng',
        sets: 4,
        reps: 'Max (hoặc 8–10)',
        rest_sec: 90,
        weight_note: 'Nếu chưa được 5 rep: dùng band trợ lực hoặc jumping pull-up',
        tips: [
          'Tay rộng hơn vai, lòng bàn tay hướng ra ngoài',
          'Kéo khuỷu tay xuống và vào người — nghĩ đến việc "bẻ cong thanh xà"',
          'Lên đến cằm qua xà, hạ xuống kiểm soát hoàn toàn',
        ],
        avoid: [
          'Không đu đưa hay dùng đà chân',
          'Không để vai nhô lên tai khi treo',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-12.svg',
      },
      {
        id: 'bent-over-row',
        name: 'Dumbbell Bent-Over Row',
        name_vi: 'Chèo tạ cúi người',
        muscle_group: 'Lưng giữa',
        sets: 4,
        reps: '10–12',
        rest_sec: 60,
        weight_note: 'Bắt đầu 10–12kg/tay, form quan trọng hơn tạ nặng',
        tips: [
          'Cúi người 45 độ, lưng thẳng, ngực hướng xuống',
          'Kéo tạ vào hông (không vào ngực)',
          'Siết lưng giữa ở điểm cao nhất, giữ 1 giây',
        ],
        avoid: [
          'Không cong lưng — chấn thương cột sống',
          'Không dùng đà giật tạ lên',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-12.svg',
      },
      {
        id: 'superman',
        name: 'Superman Hold',
        name_vi: 'Superman (Lưng dưới)',
        muscle_group: 'Lưng dưới',
        sets: 3,
        reps: '15',
        rest_sec: 45,
        weight_note: 'Bodyweight — giữ mỗi rep 2 giây',
        tips: [
          'Nằm sấp, tay duỗi về phía trước',
          'Nâng tay và chân lên cùng lúc',
          'Siết mông và lưng khi nâng',
        ],
        avoid: [
          'Không nhìn thẳng lên — giữ cổ trung lập',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-10.svg',
      },
      {
        id: 'tricep-dip',
        name: 'Tricep Dip',
        name_vi: 'Chống đẩy sau (Tay ba đầu)',
        muscle_group: 'Tay sau (Tricep)',
        sets: 4,
        reps: '12–15',
        rest_sec: 60,
        weight_note: 'Dùng ghế hoặc mặt phẳng nâng cao, bodyweight',
        tips: [
          'Tay đặt sau lưng trên ghế, ngón tay hướng về phía trước',
          'Hạ người xuống khuỷu 90 độ, đẩy lên bằng tay sau',
          'Giữ lưng sát mép ghế — không để bẻ người về trước',
        ],
        avoid: [
          'Không hạ quá thấp — áp lực vai quá lớn',
          'Không để vai nhô lên tai',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-5.svg',
      },
      {
        id: 'face-pull-band',
        name: 'Face Pull (Band)',
        name_vi: 'Kéo dây vào mặt',
        muscle_group: 'Vai sau + Lưng trên',
        sets: 3,
        reps: '15',
        rest_sec: 45,
        weight_note: 'Dùng resistance band nhẹ-vừa',
        tips: [
          'Kéo dây về phía tai, khuỷu cao hơn vai',
          'Siết vai sau và xoay ngoài ở điểm cuối',
        ],
        avoid: [
          'Không kéo về phía cổ — kéo về phía tai',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-2.svg',
      },
    ],
  },
  {
    day: 'T4',
    day_vi: 'Thứ 4',
    muscle_groups: 'Chân + Core',
    duration_min: '40–45',
    exercises: [
      {
        id: 'squat',
        name: 'Bodyweight / Goblet Squat',
        name_vi: 'Squat (Tự trọng / Goblet)',
        muscle_group: 'Đùi trước + Mông',
        sets: 4,
        reps: '15–20',
        rest_sec: 60,
        weight_note: 'Bắt đầu bodyweight, thêm tạ đơn 10–15kg khi thành thạo',
        tips: [
          'Chân rộng bằng vai, mũi chân hơi xòe ra ngoài',
          'Hạ xuống như ngồi vào ghế — gối không vượt quá mũi chân',
          'Giữ lưng thẳng, ngực hướng lên',
        ],
        avoid: [
          'Không để gối sập vào trong (valgus)',
          'Không cong lưng khi đứng dậy',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-10.svg',
      },
      {
        id: 'reverse-lunge',
        name: 'Reverse Lunge',
        name_vi: 'Bước lùi (Lunge ngược)',
        muscle_group: 'Đùi + Mông',
        sets: 3,
        reps: '12/chân',
        rest_sec: 60,
        weight_note: 'Bodyweight trước, thêm tạ đơn 6–8kg/tay sau',
        tips: [
          'Bước chân sau lùi, hạ gối xuống gần sàn',
          'Gối trước không vượt mũi chân',
          'Đẩy gót chân trước để đứng lên',
        ],
        avoid: [
          'Không để thân người đổ về trước',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-11.svg',
      },
      {
        id: 'glute-bridge',
        name: 'Glute Bridge / Hip Thrust',
        name_vi: 'Nâng hông',
        muscle_group: 'Mông + Đùi sau',
        sets: 4,
        reps: '15',
        rest_sec: 45,
        weight_note: 'Bắt đầu bodyweight, thêm tạ đĩa lên bụng khi dễ',
        tips: [
          'Nằm ngửa, gối gập 90 độ, đẩy hông lên',
          'Siết mông tối đa ở đỉnh — giữ 2 giây',
          'Hạ xuống không chạm sàn hẳn để giữ tension',
        ],
        avoid: [
          'Không dùng lưng để đẩy — đẩy bằng gót chân và mông',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-8.svg',
      },
      {
        id: 'plank',
        name: 'Plank + Variations',
        name_vi: 'Plank',
        muscle_group: 'Core',
        sets: 3,
        reps: '30–60 giây',
        rest_sec: 45,
        weight_note: 'Bodyweight — mục tiêu đạt 60 giây/set',
        tips: [
          'Khuỷu tay dưới vai, người thẳng như tấm ván',
          'Siết core, mông, và đùi đồng thời',
          'Thở đều — đừng nín thở',
        ],
        avoid: [
          'Không để hông cao hoặc võng xuống',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-6.svg',
      },
      {
        id: 'hanging-knee-raise',
        name: 'Hanging Knee Raise',
        name_vi: 'Nâng gối treo xà',
        muscle_group: 'Bụng dưới',
        sets: 3,
        reps: '12–15',
        rest_sec: 45,
        weight_note: 'Bodyweight — treo xà đơn',
        tips: [
          'Treo xà, nâng gối lên 90 độ',
          'Siết bụng — không swing người',
          'Hạ chậm rãi 2–3 giây',
        ],
        avoid: [
          'Không dùng đà đu đưa để nâng gối lên',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-6.svg',
      },
    ],
  },
  {
    day: 'T5',
    day_vi: 'Thứ 5',
    muscle_groups: 'Tay trước + Vai',
    duration_min: '40',
    exercises: [
      {
        id: 'bicep-curl',
        name: 'Dumbbell Bicep Curl',
        name_vi: 'Curl tay trước',
        muscle_group: 'Bicep',
        sets: 4,
        reps: '12',
        rest_sec: 60,
        weight_note: 'Bắt đầu 8–10kg/tay',
        tips: [
          'Khuỷu tay sát hông, không di chuyển',
          'Xoay bàn tay ra ngoài khi curl lên',
          'Siết đỉnh 1 giây, hạ xuống chậm 3 giây',
        ],
        avoid: [
          'Không lắc người — cô lập hoàn toàn tay trước',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-1.svg',
      },
      {
        id: 'hammer-curl',
        name: 'Hammer Curl',
        name_vi: 'Hammer Curl',
        muscle_group: 'Bicep + Cánh tay ngoài',
        sets: 3,
        reps: '12',
        rest_sec: 60,
        weight_note: '8–10kg/tay',
        tips: [
          'Giữ tạ theo chiều dọc (như cầm búa)',
          'Khuỷu tay cố định, curl lên và xuống',
        ],
        avoid: [
          'Không dùng đà vai để đẩy tạ',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-1.svg',
      },
      {
        id: 'overhead-press',
        name: 'Dumbbell Overhead Press',
        name_vi: 'Đẩy tạ trên đầu',
        muscle_group: 'Vai trước + Vai giữa',
        sets: 4,
        reps: '10–12',
        rest_sec: 60,
        weight_note: 'Bắt đầu 8–12kg/tay',
        tips: [
          'Ngồi hoặc đứng, tạ ngang vai khuỷu 90 độ',
          'Đẩy thẳng lên, không khóa khuỷu hoàn toàn',
          'Hạ xuống kiểm soát, không rơi tự do',
        ],
        avoid: [
          'Không ưỡn lưng quá nhiều khi đẩy',
          'Không để vai nhô lên',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-2.svg',
      },
      {
        id: 'front-raise',
        name: 'Front Raise',
        name_vi: 'Nâng tạ ra trước',
        muscle_group: 'Vai trước',
        sets: 3,
        reps: '12',
        rest_sec: 45,
        weight_note: '5–8kg/tay',
        tips: [
          'Giữ tạ trước đùi, nâng thẳng lên ngang vai',
          'Không xoay người, không lắc',
        ],
        avoid: [
          'Không nâng quá ngang vai — không cần thiết, hại khớp',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-2.svg',
      },
      {
        id: 'reverse-curl',
        name: 'Reverse Curl',
        name_vi: 'Curl ngược (Cẳng tay)',
        muscle_group: 'Cẳng tay',
        sets: 3,
        reps: '12',
        rest_sec: 45,
        weight_note: '5–8kg/tay',
        tips: [
          'Lòng bàn tay hướng xuống (pronated grip)',
          'Curl lên như bình thường, cẳng tay co lại',
        ],
        avoid: [
          'Không dùng tạ quá nặng — cổ tay dễ chấn thương',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-1.svg',
      },
    ],
  },
  {
    day: 'T6',
    day_vi: 'Thứ 6',
    muscle_groups: 'HIIT Toàn thân',
    duration_min: '30–35',
    exercises: [
      {
        id: 'jumping-jacks',
        name: 'Jumping Jacks',
        name_vi: 'Nhảy chân tay',
        muscle_group: 'Toàn thân',
        sets: 3,
        reps: '30 giây',
        rest_sec: 15,
        weight_note: 'HIIT: 30 giây làm, 15 giây nghỉ',
        tips: ['Nhảy nhịp nhàng, không đổ người về phía trước'],
        avoid: ['Không tiếp đất bằng gót chân'],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-10.svg',
      },
      {
        id: 'burpee',
        name: 'Burpee',
        name_vi: 'Burpee',
        muscle_group: 'Toàn thân',
        sets: 3,
        reps: '30 giây',
        rest_sec: 30,
        weight_note: 'HIIT — tốc độ vừa phải, form trên hết',
        tips: [
          'Squat xuống, chống tay, đá chân ra sau, push-up, nhảy lên',
          'Kết hợp nhịp nhàng không ngắt',
        ],
        avoid: [
          'Không đua tốc độ đến mức mất form',
          'Không hạ lưng xuống khi plank',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-10.svg',
      },
      {
        id: 'mountain-climber',
        name: 'Mountain Climber',
        name_vi: 'Leo núi',
        muscle_group: 'Core + Toàn thân',
        sets: 3,
        reps: '30 giây',
        rest_sec: 15,
        weight_note: 'HIIT — càng nhanh càng tốt',
        tips: [
          'Tay thẳng, người plank chuẩn',
          'Kéo gối về ngực xen kẽ nhanh',
        ],
        avoid: ['Không để hông nhô lên'],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-6.svg',
      },
      {
        id: 'squat-jump',
        name: 'Jump Squat',
        name_vi: 'Squat nhảy',
        muscle_group: 'Chân + Cardio',
        sets: 3,
        reps: '30 giây',
        rest_sec: 30,
        weight_note: 'Bodyweight — bùng nổ',
        tips: [
          'Hạ xuống squat sâu, đẩy bùng nổ lên cao',
          'Tiếp đất nhẹ nhàng bằng nửa trước bàn chân',
        ],
        avoid: ['Không tiếp đất cứng bằng gót'],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-11.svg',
      },
      {
        id: 'high-knees',
        name: 'High Knees',
        name_vi: 'Chạy tại chỗ nâng cao gối',
        muscle_group: 'Cardio + Core',
        sets: 3,
        reps: '30 giây',
        rest_sec: 15,
        weight_note: 'HIIT tốc độ cao',
        tips: [
          'Nâng gối ngang hông, không thấp hơn',
          'Đánh tay mạnh để tăng tốc',
        ],
        avoid: ['Không nhìn xuống đất'],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-10.svg',
      },
    ],
  },
  {
    day: 'T7',
    day_vi: 'Thứ 7',
    muscle_groups: 'Nhảy dây + Core nhẹ',
    duration_min: '20–25',
    exercises: [
      {
        id: 'jump-rope-basic',
        name: 'Jump Rope - Basic',
        name_vi: 'Nhảy dây cơ bản',
        muscle_group: 'Cardio',
        sets: 5,
        reps: '2 phút',
        rest_sec: 60,
        weight_note: 'Target: 5 × 2 phút = 10 phút nhảy dây tổng',
        tips: [
          'Nhảy nhẹ nhàng, tiếp đất bằng nửa trước bàn chân',
          'Khuỷu tay gần hông, cổ tay xoay dây',
          'Nhịp thở đều — đừng nín thở',
        ],
        avoid: [
          'Không nhảy quá cao — tốn năng lượng vô ích',
          'Không tiếp đất bằng gót chân',
        ],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-10.svg',
      },
      {
        id: 'dead-bug',
        name: 'Dead Bug',
        name_vi: 'Dead Bug (Core)',
        muscle_group: 'Core sâu',
        sets: 3,
        reps: '10/bên',
        rest_sec: 45,
        weight_note: 'Bodyweight — tập chậm, cảm nhận core',
        tips: [
          'Nằm ngửa, tay và chân lên trên',
          'Hạ tay phải + chân trái cùng lúc, không chạm sàn',
          'Giữ lưng dưới dán sàn suốt bài',
        ],
        avoid: ['Không để lưng dưới cong lên khỏi sàn'],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-6.svg',
      },
      {
        id: 'side-plank',
        name: 'Side Plank',
        name_vi: 'Plank nghiêng',
        muscle_group: 'Core bên (Obliques)',
        sets: 3,
        reps: '30 giây/bên',
        rest_sec: 30,
        weight_note: 'Bodyweight',
        tips: [
          'Khuỷu tay dưới vai, người thẳng từ đầu đến gót',
          'Hông không võng xuống',
        ],
        avoid: ['Không để vai gần tai'],
        gif_url: 'https://wger.de/static/images/muscles/main/muscle-6.svg',
      },
    ],
  },
]

export const MEAL_PLAN = [
  { meal: 'Sáng', items: 'Bún bò / bánh mì + chả + cà phê ít sữa', calories: 500, protein: 25 },
  { meal: 'Trưa', items: 'Cơm + thức ăn (tăng phần thịt) + cà phê ít sữa', calories: 600, protein: 35 },
  { meal: 'Chiều', items: 'Cà phê đen / trà xanh / trà oolong không đường', calories: 5, protein: 0 },
  { meal: 'Pre-workout', items: '1–2 chuối (trước tập 30–45 phút)', calories: 175, protein: 2 },
  { meal: 'Sau tập', items: 'Whey 1 scoop pha nước', calories: 120, protein: 25 },
  { meal: 'Tối', items: '200g cơm + 90g cá ngừ + 2 trứng luộc', calories: 520, protein: 42 },
]

export const DAILY_TARGET = { calories: 1920, protein: 130 }
export const GOAL = { start_weight: 79, target_weight: 64, target_bodyfat_min: 10, target_bodyfat_max: 12 }
