export type Exercise = {
  id: string
  name: string
  name_vi: string
  muscle_group: string
  sets: number
  reps: string
  rest_sec: number
  weight_note: string
  tips: string[]
  avoid: string[]
  gif_url: string
  superset?: string | null
}

export type WorkoutDay = {
  day: string
  day_vi: string
  muscle_groups: string
  duration_min: string
  note: string
  exercises: Exercise[]
}

const BASE = '/gifs/'

export const WORKOUT_PLAN: WorkoutDay[] = [
  {
    day: 'T2',
    day_vi: 'Thứ 2',
    muscle_groups: 'Ngực + Vai + Tricep',
    duration_min: '50',
    note: 'Tập theo superset A+B để tăng cường độ dù tạ nhẹ',
    exercises: [
      {
        id: 'chest-press-flat',
        name: 'Dumbbell Bench Press',
        name_vi: 'Đẩy tạ đôi (ghế flat)',
        muscle_group: 'Ngực',
        sets: 4,
        reps: '12–15',
        rest_sec: 45,
        weight_note: 'Dùng 7–9kg/tay. Tempo 3-1-1: hạ 3 giây, giữ 1 giây dưới, đẩy lên 1 giây.',
        tips: [
          'Nằm trên ghế flat, tạ ngang ngực, khuỷu 45 độ với thân',
          'Đẩy lên và vào nhau (không khóa khuỷu), siết ngực 1 giây ở đỉnh',
          'Hạ xuống chậm — đây là lúc cơ phát triển nhiều nhất',
        ],
        avoid: [
          'Không để khuỷu bè 90 độ ra ngoài — hại vai',
          'Không nảy tạ lên bằng ngực',
        ],
        gif_url: BASE + 'chest-press.gif',
        superset: 'A',
      },
      {
        id: 'lateral-raise',
        name: 'Dumbbell Lateral Raise',
        name_vi: 'Nâng tạ sang ngang',
        muscle_group: 'Vai giữa',
        sets: 4,
        reps: '15–20',
        rest_sec: 45,
        weight_note: 'Dùng 3–5kg/tay. Nhẹ hơn mày nghĩ là đúng — cơ vai giữa nhỏ.',
        tips: [
          'Nghiêng người ra trước nhẹ 10–15 độ',
          'Nâng tạ hình vòng cung rộng ra hai bên, dừng ngang vai',
          'Ngón út cao hơn ngón cái khi nâng (internal rotation nhẹ)',
        ],
        avoid: [
          'Không nhún vai — loại cơ bẫy ra khỏi bài',
          'Không swing người để nâng',
        ],
        gif_url: BASE + 'lateral-raise.gif',
        superset: 'A',
      },
      {
        id: 'incline-press',
        name: 'Dumbbell Incline Press',
        name_vi: 'Đẩy tạ đôi (ghế 45°)',
        muscle_group: 'Ngực trên',
        sets: 3,
        reps: '12',
        rest_sec: 60,
        weight_note: 'Dùng 6–8kg/tay. Ngực trên yếu hơn — dùng tạ nhẹ hơn flat press.',
        tips: [
          'Ghế ở 45 độ, tạ cầm ở góc 75 độ so với thân',
          'Đẩy thẳng lên và hơi vào trong',
          'Focus cảm nhận phần trên ngực căng ra',
        ],
        avoid: [
          'Không để ghế quá dốc (>60°) — thành bài vai',
          'Không để lưng rời ghế',
        ],
        gif_url: BASE + 'incline-press.gif',
        superset: 'B',
      },
      {
        id: 'overhead-press',
        name: 'Dumbbell Overhead Press',
        name_vi: 'Đẩy tạ trên đầu',
        muscle_group: 'Vai trước + giữa',
        sets: 3,
        reps: '12',
        rest_sec: 60,
        weight_note: 'Dùng 7–9kg/tay. Tăng lên khi làm đủ 12 rep dễ dàng.',
        tips: [
          'Ngồi thẳng trên ghế, tạ ngang tai khuỷu 90 độ',
          'Đẩy thẳng lên, không khóa khuỷu hoàn toàn',
          'Hạ xuống chậm 3 giây — không rơi tự do',
        ],
        avoid: [
          'Không ưỡn lưng để đẩy tạ',
          'Không để cổ tay gãy ra sau',
        ],
        gif_url: BASE + 'overhead-press.gif',
        superset: 'B',
      },
      {
        id: 'tricep-kickback',
        name: 'Tricep Kickback',
        name_vi: 'Kickback tay sau (ghế nghiêng)',
        muscle_group: 'Tricep',
        sets: 3,
        reps: '15/tay',
        rest_sec: 45,
        weight_note: 'Dùng 4–6kg/tay. Bài này cần cô lập, không cần nặng.',
        tips: [
          'Một tay chống lên ghế, lưng song song sàn',
          'Khuỷu cố định ngang hông, duỗi tay ra thẳng',
          'Siết tricep 1 giây ở điểm duỗi thẳng',
        ],
        avoid: [
          'Không để khuỷu rớt xuống khi đẩy',
          'Không swing cánh tay',
        ],
        gif_url: BASE + 'tricep-kickback.gif',
        superset: null,
      },
    ],
  },
  {
    day: 'T3',
    day_vi: 'Thứ 3',
    muscle_groups: 'Lưng + Bicep',
    duration_min: '50',
    note: 'Nhóm cơ lớn — tập nặng tương đối, tempo chậm để bù tạ nhẹ',
    exercises: [
      {
        id: 'one-arm-row',
        name: 'Dumbbell One Arm Row',
        name_vi: 'Chèo tạ một tay (chống ghế)',
        muscle_group: 'Lưng rộng',
        sets: 4,
        reps: '10–12/tay',
        rest_sec: 60,
        weight_note: 'Dùng 9kg/tay (tạ nặng nhất). Đây là bài chính cho lưng.',
        tips: [
          'Một đầu gối + một tay chống ghế, lưng song song sàn',
          'Kéo tạ về hông (không về ngực) — tưởng tượng bỏ tay vào túi quần',
          'Siết lưng 1 giây ở đỉnh, hạ xuống 3 giây',
        ],
        avoid: [
          'Không rotate thân mình khi kéo — mất cô lập lưng',
          'Không kéo bằng cơ tay — dẫn bằng khuỷu',
        ],
        gif_url: BASE + 'one-arm-row.gif',
        superset: 'A',
      },
      {
        id: 'bicep-curl',
        name: 'Dumbbell Bicep Curl',
        name_vi: 'Curl tay trước',
        muscle_group: 'Bicep',
        sets: 4,
        reps: '12',
        rest_sec: 60,
        weight_note: 'Dùng 7–9kg/tay. Supinate (xoay ngửa bàn tay) khi curl lên.',
        tips: [
          'Khuỷu cố định sát hông — không di chuyển',
          'Xoay bàn tay ra ngoài khi curl lên',
          'Hạ xuống 3 giây — đây là phần eccentric quan trọng',
        ],
        avoid: [
          'Không swing người để "ăn gian" — vô nghĩa',
          'Không để khuỷu bị đẩy ra trước',
        ],
        gif_url: BASE + 'bicep-curl.gif',
        superset: 'A',
      },
      {
        id: 'incline-row',
        name: 'Incline Dumbbell Row',
        name_vi: 'Chèo tạ nằm nghiêng (ghế 45°)',
        muscle_group: 'Lưng giữa + Rhomboid',
        sets: 3,
        reps: '15',
        rest_sec: 45,
        weight_note: 'Dùng 6–8kg/tay. Nằm sấp trên ghế nghiêng.',
        tips: [
          'Nằm sấp trên ghế 45°, tạ buông thẳng xuống',
          'Kéo tạ lên bằng cách siết bả vai lại với nhau',
          'Khuỷu hướng ra ngoài 45 độ (không sát người như row thường)',
        ],
        avoid: [
          'Không dùng lực đà lắc người',
          'Không để bả vai không siết — mất activation lưng giữa',
        ],
        gif_url: BASE + 'incline-row.gif',
        superset: 'B',
      },
      {
        id: 'hammer-curl',
        name: 'Hammer Curl',
        name_vi: 'Hammer Curl',
        muscle_group: 'Bicep + Brachialis',
        sets: 3,
        reps: '12',
        rest_sec: 45,
        weight_note: 'Dùng 7–9kg/tay. Tạ cầm thẳng như búa.',
        tips: [
          'Giữ tạ theo chiều dọc suốt bài (neutral grip)',
          'Khuỷu cố định, curl chậm lên',
          'Bài này train Brachialis — tạo chiều sâu cho cánh tay',
        ],
        avoid: [
          'Không xoay cổ tay — phải giữ neutral grip suốt',
        ],
        gif_url: BASE + 'hammer-curl.gif',
        superset: 'B',
      },
      {
        id: 'dumbbell-shrug',
        name: 'Dumbbell Shrug',
        name_vi: 'Nhún vai tạ đôi',
        muscle_group: 'Bẫy (Trapezius)',
        sets: 3,
        reps: '20',
        rest_sec: 30,
        weight_note: 'Dùng 9kg/tay. Bài đơn giản nhưng cần tập trung cơ bẫy.',
        tips: [
          'Đứng thẳng, nhún vai thẳng lên (không xoay)',
          'Giữ ở đỉnh 2 giây — siết cơ bẫy',
          'Hạ xuống hết cỡ để stretch',
        ],
        avoid: [
          'Không xoay vai tròn — không có lợi, dễ chấn thương',
        ],
        gif_url: BASE + 'shrug.gif',
        superset: null,
      },
      {
        id: 'superman',
        name: 'Superman Hold',
        name_vi: 'Superman Hold (Lưng dưới)',
        muscle_group: 'Lưng dưới',
        sets: 3,
        reps: '15',
        rest_sec: 45,
        weight_note: 'Bodyweight — nằm sàn hoặc ghế phẳng, không cần tạ',
        tips: [
          'Nằm sấp, tay duỗi thẳng ra trước hoặc để sau gáy',
          'Nâng đồng thời ngực và 2 chân lên khỏi sàn — giữ 3 giây',
          'Siết erector spinae (cơ dọc cột sống) tối đa ở đỉnh',
          'Hạ xuống chậm, không đập người xuống sàn',
        ],
        avoid: [
          'Không nhìn thẳng lên — cổ giữ trung lập, mắt nhìn xuống sàn',
          'Không nín thở — thở ra khi nâng lên',
        ],
        gif_url: BASE + 'superman.gif',
        superset: null,
      },
    ],
  },
  {
    day: 'T4',
    day_vi: 'Thứ 4',
    muscle_groups: 'Chân + Mông + Core',
    duration_min: '45',
    note: 'Chân là nhóm cơ lớn nhất — đốt mỡ nhiều nhất. Tạ nhẹ bù bằng rep cao',
    exercises: [
      {
        id: 'goblet-squat',
        name: 'Dumbbell Goblet Squat',
        name_vi: 'Goblet Squat',
        muscle_group: 'Đùi trước + Mông',
        sets: 4,
        reps: '20',
        rest_sec: 60,
        weight_note: 'Dùng 9kg (1 tạ cầm trước ngực). Bù tạ nhẹ bằng 20 reps.',
        tips: [
          'Ôm tạ đứng dọc trước ngực, chân rộng bằng vai',
          'Hạ xuống sâu — đùi song song hoặc thấp hơn sàn',
          'Gối theo hướng mũi chân, không sập vào trong',
        ],
        avoid: [
          'Không để lưng cong — ngực phải luôn hướng lên',
          'Không nhón gót chân lên',
        ],
        gif_url: BASE + 'goblet-squat.gif',
        superset: 'A',
      },
      {
        id: 'rdl',
        name: 'Romanian Deadlift (RDL)',
        name_vi: 'Romanian Deadlift',
        muscle_group: 'Đùi sau + Mông',
        sets: 4,
        reps: '15',
        rest_sec: 60,
        weight_note: 'Dùng 9kg/tay. Bài training hamstring quan trọng nhất.',
        tips: [
          'Đứng thẳng, tạ trước đùi, chân rộng hông',
          'Đẩy hông ra sau khi hạ — không gập đầu gối nhiều',
          'Hạ tạ dọc theo chân đến khi cảm nhận hamstring căng',
        ],
        avoid: [
          'Không cong lưng — giữ lưng thẳng suốt',
          'Không hạ tạ quá thấp nếu lưng bắt đầu cong',
        ],
        gif_url: BASE + 'rdl.gif',
        superset: 'A',
      },
      {
        id: 'reverse-lunge',
        name: 'Dumbbell Reverse Lunge',
        name_vi: 'Lunge bước lùi',
        muscle_group: 'Đùi + Mông',
        sets: 3,
        reps: '12/chân',
        rest_sec: 60,
        weight_note: 'Dùng 6–8kg/tay. Bước lùi thay vì bước tới — an toàn hơn cho gối.',
        tips: [
          'Bước một chân ra sau, hạ gối xuống gần sàn',
          'Gối trước thẳng hàng với mũi chân, không vượt qua',
          'Đẩy từ gót chân trước để đứng lên',
        ],
        avoid: [
          'Không để thân người đổ về trước',
          'Không để gối trước vượt qua mũi chân',
        ],
        gif_url: BASE + 'reverse-lunge.gif',
        superset: 'B',
      },
      {
        id: 'glute-bridge',
        name: 'Glute Bridge (ghế + tạ)',
        name_vi: 'Nâng hông có tạ',
        muscle_group: 'Mông',
        sets: 3,
        reps: '20',
        rest_sec: 45,
        weight_note: 'Đặt 1 tạ 9kg lên bụng dưới. Vai tựa mép ghế.',
        tips: [
          'Vai tựa ghế, gối gập 90°, tạ đặt lên xương chậu',
          'Đẩy hông lên cao, siết mông tối đa ở đỉnh — giữ 2 giây',
          'Hạ xuống không chạm sàn (tension liên tục)',
        ],
        avoid: [
          'Không dùng lưng để đẩy — phải cảm nhận mông làm việc',
          'Không để đầu gối đổ vào trong',
        ],
        gif_url: BASE + 'glute-bridge.gif',
        superset: 'B',
      },
      {
        id: 'plank-row',
        name: 'Plank + Dumbbell Row',
        name_vi: 'Plank chèo tạ',
        muscle_group: 'Core + Lưng',
        sets: 3,
        reps: '8/tay',
        rest_sec: 45,
        weight_note: 'Dùng 5–7kg. Bài này train core ổn định cực kỳ hiệu quả.',
        tips: [
          'Tư thế plank cao (tay thẳng), tạ ở 2 bên',
          'Giữ hông hoàn toàn cân bằng khi kéo tạ lên',
          'Kéo tạ về hông, khuỷu cạo dọc sườn',
        ],
        avoid: [
          'Không để hông xoay hay nâng lên khi row',
          'Bài này cần balance hơn sức mạnh — đừng dùng tạ quá nặng',
        ],
        gif_url: BASE + 'plank.gif',
        superset: null,
      },
      {
        id: 'back-extension',
        name: 'Roman Chair Back Extension',
        name_vi: 'Back Extension (ghế Roman) ⭐',
        muscle_group: 'Lưng dưới',
        sets: 4,
        reps: '15–20',
        rest_sec: 60,
        weight_note: 'Tuần 1–2: bodyweight · Tuần 3+: ôm 1 tạ 5–9kg trước ngực',
        tips: [
          'Điều chỉnh ghế để pad nằm ngay dưới xương chậu — không phải ở bụng',
          'Bắt đầu ở tư thế cúi người 90° xuống, lưng thẳng',
          'Nâng thân lên bằng cách siết erector spinae và mông — không dùng đà',
          'Dừng khi thân thẳng hàng với chân, giữ 2 giây, hạ xuống chậm 3 giây',
        ],
        avoid: [
          'Không hyperextend (ưỡn lưng quá ra sau đỉnh) — áp lực cột sống rất lớn',
          'Không cong lưng tròn khi hạ xuống — lưng thẳng suốt bài',
          'Nếu cảm thấy đau lưng (không phải mỏi cơ) — dừng ngay, kiểm tra setup ghế',
        ],
        gif_url: BASE + 'back-extension.gif',
        superset: null,
      },
      {
        id: 'bird-dog',
        name: 'Bird Dog',
        name_vi: 'Bird Dog (lưng dưới + core ổn định)',
        muscle_group: 'Lưng dưới + Core',
        sets: 3,
        reps: '12/bên',
        rest_sec: 45,
        weight_note: 'Bodyweight — bài rehabilitation chuẩn y khoa cho đau lưng do ngồi nhiều',
        tips: [
          'Quỳ 4 điểm: tay thẳng dưới vai, gối thẳng dưới hông',
          'Duỗi đồng thời tay phải + chân trái ra thẳng, giữ 3 giây',
          'Lưng phẳng như mặt bàn suốt bài — đặt ly nước lên lưng để kiểm tra',
          'Siết core và mông khi giữ tư thế',
        ],
        avoid: [
          'Không để hông xoay hay nâng lên khi duỗi chân',
          'Không vươn tay chân quá cao — ngang thân người là đủ',
        ],
        gif_url: BASE + 'dead-bug.gif',
        superset: null,
      },
    ],
  },
  {
    day: 'T5',
    day_vi: 'Thứ 5',
    muscle_groups: 'Vai (toàn bộ) + Core',
    duration_min: '40',
    note: 'Vai 3 đầu: trước, giữa, sau — tất cả đều train hôm nay',
    exercises: [
      {
        id: 'arnold-press',
        name: 'Arnold Press',
        name_vi: 'Arnold Press',
        muscle_group: 'Vai 3 đầu',
        sets: 4,
        reps: '12',
        rest_sec: 60,
        weight_note: 'Dùng 7–9kg/tay. Bài tốt nhất cho vai toàn diện với tạ nhẹ.',
        tips: [
          'Bắt đầu tay ngửa (như đỉnh bicep curl), tạ ngang cằm',
          'Xoay tay ra ngoài khi đẩy lên — kết thúc lòng bàn tay hướng ra',
          'Hạ xuống theo chiều ngược lại',
        ],
        avoid: [
          'Không đẩy quá nhanh — mất movement pattern',
          'Không để lưng ưỡn quá mức',
        ],
        gif_url: BASE + 'arnold-press.gif',
        superset: null,
      },
      {
        id: 'lateral-raise-t5',
        name: 'Lateral Raise + Front Raise (superset)',
        name_vi: 'Nâng ngang + Nâng trước (superset)',
        muscle_group: 'Vai giữa + Vai trước',
        sets: 3,
        reps: '12+12',
        rest_sec: 60,
        weight_note: 'Lateral: 3–5kg | Front: 5–6kg. Làm lateral trước, không nghỉ, làm front.',
        tips: [
          'Lateral: tạo vòng cung rộng, nghiêng nhẹ về trước',
          'Front: tạ cạnh đùi, nâng thẳng lên ngang vai',
          'Hạ chậm 3 giây cho cả 2 bài',
        ],
        avoid: [
          'Không swing người cho cả 2 bài',
          'Không nâng quá ngang vai — hại khớp vai',
        ],
        gif_url: BASE + 'lateral-raise.gif',
        superset: 'A',
      },
      {
        id: 'reverse-fly',
        name: 'Bent-Over Reverse Fly',
        name_vi: 'Bay ngược cúi người (Vai sau)',
        muscle_group: 'Vai sau',
        sets: 4,
        reps: '15–20',
        rest_sec: 45,
        weight_note: 'Dùng 3–5kg/tay. Vai sau rất yếu — bắt đầu nhẹ.',
        tips: [
          'Cúi người 45°, lưng thẳng, nhìn xuống',
          'Nâng tạ ra hai bên theo đường cong, khuỷu hơi cong',
          'Siết vai sau và bả vai lại với nhau ở đỉnh',
        ],
        avoid: [
          'Không dùng tạ quá nặng — vai sau nhỏ và dễ chấn thương',
          'Không để cổ căng — nhìn xuống sàn',
        ],
        gif_url: BASE + 'reverse-fly.gif',
        superset: 'B',
      },
      {
        id: 'upright-row',
        name: 'Dumbbell Upright Row',
        name_vi: 'Kéo đứng lên cằm',
        muscle_group: 'Vai giữa + Bẫy',
        sets: 3,
        reps: '12',
        rest_sec: 45,
        weight_note: 'Dùng 6–8kg/tay. Kéo lên đến ngang cằm.',
        tips: [
          'Tạ trước đùi, khuỷu dẫn lên cao',
          'Kéo tạ dọc theo người lên đến cằm',
          'Khuỷu luôn cao hơn tay',
        ],
        avoid: [
          'Không kéo rộng tay ra ngoài — hại vai',
          'Không kéo quá cao — đến cằm là đủ',
        ],
        gif_url: BASE + 'upright-row.gif',
        superset: 'B',
      },
      {
        id: 'dead-bug-t5',
        name: 'Dead Bug + Plank hold',
        name_vi: 'Dead Bug + Plank (Core)',
        muscle_group: 'Core sâu',
        sets: 3,
        reps: '10/bên + 30 giây plank',
        rest_sec: 45,
        weight_note: 'Bodyweight. Kết hợp stability và endurance cho core.',
        tips: [
          'Dead bug: nằm ngửa, hạ tay + chân đối diện không chạm sàn',
          'Lưng dưới phải dán sàn suốt bài',
          'Vào plank ngay sau dead bug không nghỉ',
        ],
        avoid: [
          'Không để lưng vồng lên khi làm dead bug',
        ],
        gif_url: BASE + 'bird-dog.gif',
        superset: null,
      },
    ],
  },
  {
    day: 'T6',
    day_vi: 'Thứ 6',
    muscle_groups: 'Full Body HIIT',
    duration_min: '35',
    note: 'Đốt mỡ cực đại — circuit 4 vòng, nghỉ ít, cường độ cao',
    exercises: [
      {
        id: 'thruster',
        name: 'Dumbbell Thruster (squat + press)',
        name_vi: 'Thruster tạ đôi (Squat + Press)',
        muscle_group: 'Toàn thân',
        sets: 4,
        reps: '12',
        rest_sec: 30,
        weight_note: 'Dùng 6–8kg/tay. Bài combo tốt nhất để đốt calo.',
        tips: [
          'Squat xuống với tạ ngang vai, đứng lên và đẩy thẳng lên trên',
          'Một động tác liên tục — không dừng ở giữa',
          'Nhịp thở: hít vào khi squat, thở ra khi press',
        ],
        avoid: [
          'Không để lưng cong khi squat',
          'Không làm quá nhanh đến mất form',
        ],
        gif_url: BASE + 'thruster.gif',
        superset: null,
      },
      {
        id: 'renegade-row',
        name: 'Renegade Row',
        name_vi: 'Renegade Row',
        muscle_group: 'Lưng + Core',
        sets: 4,
        reps: '8/tay',
        rest_sec: 30,
        weight_note: 'Dùng 5–7kg/tay. Khó hơn tưởng — chân rộng để ổn định.',
        tips: [
          'Plank cao với tạ, chân rộng bằng vai hoặc hơn',
          'Kéo tạ lên từng tay, hông không xoay',
          'Core cứng như đá suốt bài',
        ],
        avoid: [
          'Không để hông nhấp nhô',
          'Không dùng tạ quá nặng — mất stability',
        ],
        gif_url: BASE + 'renegade-row.gif',
        superset: null,
      },
      {
        id: 'kb-swing',
        name: 'Dumbbell Swing (Romanian)',
        name_vi: 'Swing tạ đôi (mô phỏng Kettlebell)',
        muscle_group: 'Mông + Tim mạch',
        sets: 4,
        reps: '20',
        rest_sec: 30,
        weight_note: 'Dùng 1 tạ 9kg (cầm 2 tay). Mô phỏng kettlebell swing.',
        tips: [
          'Đứng rộng, cầm tạ 2 tay, kẹp giữa 2 chân',
          'Đẩy hông ra sau mạnh rồi snap hông về trước',
          'Lực từ hông và mông — không phải tay',
        ],
        avoid: [
          'Không squat xuống — đây là hip hinge, không phải squat',
          'Không để tạ bay quá cao đầu — ngang vai là đủ',
        ],
        gif_url: BASE + 'kb-swing.gif',
        superset: null,
      },
      {
        id: 'burpee-curl',
        name: 'Burpee + Dumbbell Curl',
        name_vi: 'Burpee + Curl',
        muscle_group: 'Toàn thân',
        sets: 4,
        reps: '8',
        rest_sec: 45,
        weight_note: 'Dùng 5kg/tay. Cardio + kháng lực kết hợp.',
        tips: [
          'Burpee bình thường, khi đứng lên thì curl luôn',
          'Tốc độ vừa phải — giữ form đẹp',
          'Thở đều, không nín thở',
        ],
        avoid: [
          'Không làm quá nhanh đến mức mất form squat khi burpee',
        ],
        gif_url: BASE + 'burpee.gif',
        superset: null,
      },
      {
        id: 'hiit-finisher',
        name: 'High Knees / Jumping Jack (finisher)',
        name_vi: 'High Knees / Nhảy chân tay (kết buổi)',
        muscle_group: 'Cardio',
        sets: 4,
        reps: '45 giây on / 15 giây off',
        rest_sec: 15,
        weight_note: 'Bodyweight. Đây là finisher — push hết sức ở đây.',
        tips: [
          'High knees: nâng gối ngang hông, đánh tay mạnh',
          'Cuối mỗi vòng circuit mới làm bài này',
          'Cố gắng giữ tốc độ cao đều suốt 45 giây',
        ],
        avoid: [
          'Không tiếp đất bằng gót chân — nhón chân',
        ],
        gif_url: BASE + 'high-knees.gif',
        superset: null,
      },
    ],
  },
]

export const GOAL = { start_weight: 79, target_weight: 64, target_bodyfat_min: 10, target_bodyfat_max: 12 }
